- XGBoost:
    colsample_bytree: [1.0]
    early_stopping_rounds: [200]
    eta: [0.01, 0.025]
    eval_metric: [auc]
    max_depth: [3,4,5,6,7,8]
    n_estimators: [1000]
    objective: ['binary:logistic']
    subsample: [0.8]
- Random Forest:
    max_depth: [5, 10, null]
    max_features: [sqrt,null, log2]
    min_samples_leaf: [1, 50]
- LightGBM:
    learning_rate: [0.01, 0.001, 0.1]
    max_depth: [5, 10, null]
    max_bin: [255, 500]
    num_leaves: [31, 100]
    reg_alpha: [0,.25, .5]
    early_stopping_round: [100]
    n_estimators: [600]
    colsample_bytree: [0.75, 1.0]
    verbosity: [-1]