- XGBoost:
    colsample_bytree: [0.8, 1.0]
    early_stopping_rounds: [200]
    eta: [0.01, 0.025]
    eval_metric: [auc]
    max_depth: [4, 6, 8]
    n_estimators: [1000]
    objective: ['binary:logistic']
    subsample: [0.8]
- Random Forest:
    max_depth: [5, 10, null]
    max_features: [sqrt,null]
    n_estimators: [100, 500, 1000]
    min_samples_leaf: [1, 50, 100]
